// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using QLBV.Models;

#nullable disable

namespace QLBV.Migrations
{
    [DbContext(typeof(QLBVContext))]
    partial class QLBVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CONCURRENCYSTAMP");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("NAME");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("NORMALIZEDNAME");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("\"NORMALIZEDNAME\" IS NOT NULL");

                    b.ToTable("ASPNETROLES", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLAIMTYPE");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLAIMVALUE");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ROLEID");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ASPNETROLECLAIMS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLAIMTYPE");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLAIMVALUE");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("USERID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ASPNETUSERCLAIMS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("LOGINPROVIDER");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("PROVIDERKEY");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PROVIDERDISPLAYNAME");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("USERID");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("ASPNETUSERLOGINS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("USERID");

                    b.Property<string>("RoleId")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ROLEID");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("ASPNETUSERROLES", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("USERID");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("LOGINPROVIDER");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NAME");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("VALUE");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("ASPNETUSERTOKENS", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.ArchiveNhanVien", b =>
                {
                    b.Property<int>("ArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ARCHIVEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchiveId"));

                    b.Property<DateTime?>("ArchivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDAT")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("HoTenNv")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("HOTENNV");

                    b.Property<string>("LoaiNhanVien")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LOAINHANVIEN");

                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MANV");

                    b.Property<string>("MaPb")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPB");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("SDT");

                    b.HasKey("ArchiveId")
                        .HasName("PK_ARCHIVE_NV");

                    b.ToTable("ARCHIVE_NHANVIEN", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ACTIONTIME")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PERFORMEDBY");

                    b.Property<string>("RecordId")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("RECORDID");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TABLENAME");

                    b.HasKey("Id")
                        .HasName("PK_AUDIT_LOG");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.BacSi", b =>
                {
                    b.Property<string>("MaBs")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MABS");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TRINHDO");

                    b.HasKey("MaBs")
                        .HasName("PK_BAC_SI");

                    b.ToTable("BACSI", (string)null);

                    b.HasData(
                        new
                        {
                            MaBs = "BS001",
                            TrinhDo = "Tiến sĩ Y khoa"
                        },
                        new
                        {
                            MaBs = "BS002",
                            TrinhDo = "Phó Giáo sư, Tiến sĩ"
                        },
                        new
                        {
                            MaBs = "BS003",
                            TrinhDo = "Bác sĩ Chuyên khoa II"
                        });
                });

            modelBuilder.Entity("QLBV.Models.BacSiArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("MaBs")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MABS");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TRINHDO");

                    b.ToTable("BACSI_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.BenhNhan", b =>
                {
                    b.Property<string>("MaBn")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MABN");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("HoTenBn")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("HOTENBN");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("SDT");

                    b.HasKey("MaBn")
                        .HasName("PK_BENH_NHAN");

                    b.ToTable("BENHNHAN", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.BenhNhanArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("HoTenBn")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("HOTENBN");

                    b.Property<string>("MaBn")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MABN");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("SDT");

                    b.ToTable("BENHNHAN_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.BoPhan", b =>
                {
                    b.Property<string>("MaBp")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MABP");

                    b.Property<string>("TenBoPhan")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TENBOPHAN");

                    b.HasKey("MaBp")
                        .HasName("PK_BO_PHAN");

                    b.ToTable("BOPHAN", (string)null);

                    b.HasData(
                        new
                        {
                            MaBp = "BPQL",
                            TenBoPhan = "Bộ phận quản lý"
                        },
                        new
                        {
                            MaBp = "BPTTDP",
                            TenBoPhan = "Bộ phận tiếp tân và điều phối"
                        },
                        new
                        {
                            MaBp = "BPDT",
                            TenBoPhan = "Bộ phận điều trị"
                        },
                        new
                        {
                            MaBp = "BPTV",
                            TenBoPhan = "Bộ phận tài vụ"
                        },
                        new
                        {
                            MaBp = "BPKT",
                            TenBoPhan = "Bộ phận kế toán"
                        },
                        new
                        {
                            MaBp = "BPDNT",
                            TenBoPhan = "Bộ phận dược – nhà thuốc"
                        });
                });

            modelBuilder.Entity("QLBV.Models.BoPhanArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("MaBp")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MABP");

                    b.Property<string>("TenBoPhan")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TENBOPHAN");

                    b.ToTable("BOPHAN_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.CaTruc", b =>
                {
                    b.Property<string>("MaCt")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MACT");

                    b.Property<string>("Nvtruc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NVTRUC");

                    b.Property<DateTime?>("ThoiGianBt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("THOIGIANBT");

                    b.Property<DateTime?>("ThoiGianKt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("THOIGIANKT");

                    b.HasKey("MaCt")
                        .HasName("PK_CA_TRUC");

                    b.HasIndex("Nvtruc");

                    b.ToTable("CATRUC", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.CaTrucArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("MaCt")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MACT");

                    b.Property<string>("Nvtruc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NVTRUC");

                    b.Property<DateTime?>("ThoiGianBt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("THOIGIANBT");

                    b.Property<DateTime?>("ThoiGianKt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("THOIGIANKT");

                    b.ToTable("CATRUC_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.ChiTietPhieuKham", b =>
                {
                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPK");

                    b.Property<string>("MaTt")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATT");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("SOTIEN");

                    b.Property<string>("TtthanhToan")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TTTHANHTOAN");

                    b.HasKey("MaPk", "MaTt")
                        .HasName("PK_CT_PHIEUKHAM");

                    b.HasIndex("MaTt");

                    b.ToTable("CHITIETPHIEUKHAM", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.ChiTietPhieuKhamArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPK");

                    b.Property<string>("MaTt")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATT");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("SOTIEN");

                    b.Property<string>("TtthanhToan")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TTTHANHTOAN");

                    b.ToTable("CHITIETPHIEUKHAM_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPHIEUNHAP");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATHUOC");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("GIANHAP");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("DATE")
                        .HasColumnName("HANSUDUNG");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SOLUONG");

                    b.HasKey("MaPhieuNhap", "MaThuoc")
                        .HasName("PK_CT_PHIEUNHAP");

                    b.HasIndex("MaThuoc");

                    b.ToTable("CHITIETPHIEUNHAP", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.ChiTietPhieuNhapArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("GIANHAP");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("DATE")
                        .HasColumnName("HANSUDUNG");

                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPHIEUNHAP");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATHUOC");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SOLUONG");

                    b.ToTable("CHITIETPHIEUNHAP_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.ChiTietToaThuoc", b =>
                {
                    b.Property<string>("MaToaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATOATHUOC");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATHUOC");

                    b.Property<string>("LieuDung")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LIEUDUNG");

                    b.Property<string>("SoLuong")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SOLUONG");

                    b.HasKey("MaToaThuoc", "MaThuoc")
                        .HasName("PK_CT_TOATHUOC");

                    b.HasIndex("MaThuoc");

                    b.ToTable("CHITIETTOATHUOC", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.ChiTietToaThuocArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("LieuDung")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LIEUDUNG");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATHUOC");

                    b.Property<string>("MaToaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATOATHUOC");

                    b.Property<string>("SoLuong")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SOLUONG");

                    b.ToTable("CHITIETTOATHUOC_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.GiaBanThuoc", b =>
                {
                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATHUOC");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAYAPDUNG");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("GIABAN");

                    b.HasKey("MaThuoc", "NgayApDung")
                        .HasName("PK_GIA_BAN");

                    b.ToTable("GIABANTHUOC", (string)null);

                    b.HasData(
                        new
                        {
                            MaThuoc = "TH001",
                            NgayApDung = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GiaBan = 15000m
                        },
                        new
                        {
                            MaThuoc = "TH002",
                            NgayApDung = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GiaBan = 35000m
                        },
                        new
                        {
                            MaThuoc = "TH003",
                            NgayApDung = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GiaBan = 20000m
                        },
                        new
                        {
                            MaThuoc = "TH004",
                            NgayApDung = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GiaBan = 18000m
                        },
                        new
                        {
                            MaThuoc = "TH005",
                            NgayApDung = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GiaBan = 22000m
                        },
                        new
                        {
                            MaThuoc = "TH006",
                            NgayApDung = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GiaBan = 28000m
                        },
                        new
                        {
                            MaThuoc = "TH007",
                            NgayApDung = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GiaBan = 16000m
                        },
                        new
                        {
                            MaThuoc = "TH008",
                            NgayApDung = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GiaBan = 40000m
                        },
                        new
                        {
                            MaThuoc = "TH009",
                            NgayApDung = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GiaBan = 25000m
                        },
                        new
                        {
                            MaThuoc = "TH010",
                            NgayApDung = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GiaBan = 19000m
                        });
                });

            modelBuilder.Entity("QLBV.Models.GiaBanThuocArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("GIABAN");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATHUOC");

                    b.Property<DateTime?>("NgayApDung")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAYAPDUNG");

                    b.ToTable("GIABANTHUOC_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.Luong", b =>
                {
                    b.Property<string>("MaLuong")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MALUONG");

                    b.Property<decimal?>("LuongCoBan")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("LUONGCOBAN");

                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MANV");

                    b.Property<int?>("Nam")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NAM");

                    b.Property<int?>("NgayCong")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NGAYCONG");

                    b.Property<decimal?>("PhuCap")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("PHUCAP");

                    b.Property<int?>("Thang")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("THANG");

                    b.Property<decimal?>("TongLuong")
                        .HasColumnType("DECIMAL(20, 2)")
                        .HasColumnName("TONGLUONG");

                    b.HasKey("MaLuong")
                        .HasName("PK_LUONG");

                    b.HasIndex("MaNv");

                    b.ToTable("LUONG", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.LuongArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<decimal?>("LuongCoBan")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("LUONGCOBAN");

                    b.Property<string>("MaLuong")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MALUONG");

                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MANV");

                    b.Property<int?>("Nam")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NAM");

                    b.Property<int?>("NgayCong")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NGAYCONG");

                    b.Property<decimal?>("PhuCap")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("PHUCAP");

                    b.Property<int?>("Thang")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("THANG");

                    b.Property<decimal?>("TongLuong")
                        .HasColumnType("DECIMAL(20, 2)")
                        .HasColumnName("TONGLUONG");

                    b.ToTable("LUONG_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MANV");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("HoTenNv")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("HOTENNV");

                    b.Property<string>("MaPb")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPB");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("SDT");

                    b.HasKey("MaNv")
                        .HasName("PK_NHAN_VIEN");

                    b.HasIndex("MaPb");

                    b.ToTable("NHANVIEN", (string)null);

                    b.HasData(
                        new
                        {
                            MaNv = "BS001",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Nguyễn Hoàng Phong",
                            MaPb = "PBKN",
                            NgaySinh = new DateTime(1980, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0987123456"
                        },
                        new
                        {
                            MaNv = "BS002",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Nguyễn Quang Ngọc",
                            MaPb = "PBKG",
                            NgaySinh = new DateTime(1975, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0912345678"
                        },
                        new
                        {
                            MaNv = "BS003",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Nguyễn Trần Gia Huy",
                            MaPb = "PBKNHI",
                            NgaySinh = new DateTime(1982, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV001",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Lê Nguyễn Minh Hoàng",
                            MaPb = "PBQLNS",
                            NgaySinh = new DateTime(1982, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV002",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Phan Võ Anh Hào",
                            MaPb = "PBQLTV",
                            NgaySinh = new DateTime(1982, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV003",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Quách Tuấn Anh",
                            MaPb = "PBQLCM",
                            NgaySinh = new DateTime(1982, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV004",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Nguyễn Văn A",
                            MaPb = "PBTTDP",
                            NgaySinh = new DateTime(1982, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV005",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Nguyễn Văn B",
                            MaPb = "PBTTV",
                            NgaySinh = new DateTime(1982, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV006",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nữ",
                            HoTenNv = "Trần Thị C",
                            MaPb = "PBKT",
                            NgaySinh = new DateTime(1982, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV007",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Lê Văn D",
                            MaPb = "PBBT",
                            NgaySinh = new DateTime(1982, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0978123456"
                        });
                });

            modelBuilder.Entity("QLBV.Models.PhieuKhamBenh", b =>
                {
                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPK");

                    b.Property<string>("Bacsi")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("BACSI");

                    b.Property<int?>("MaSoKham")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MASOKHAM");

                    b.Property<DateTime?>("NgayKham")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAYKHAM");

                    b.Property<string>("NguoiKham")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NGUOIKHAM");

                    b.Property<string>("TrieuChung")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TRIEUCHUNG");

                    b.HasKey("MaPk")
                        .HasName("PK_PHIEU_KHAM");

                    b.HasIndex("Bacsi");

                    b.HasIndex("MaSoKham");

                    b.HasIndex("NguoiKham");

                    b.ToTable("PHIEUKHAMBENH", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.PhieuKhamBenhArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("Bacsi")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("BACSI");

                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPK");

                    b.Property<DateTime?>("NgayKham")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAYKHAM");

                    b.Property<string>("NguoiKham")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NGUOIKHAM");

                    b.Property<string>("TrieuChung")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TRIEUCHUNG");

                    b.ToTable("PHIEUKHAMBENH_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.PhieuNhapThuoc", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPHIEUNHAP");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAYNHAP");

                    b.Property<string>("NhaCungCap")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NHACUNGCAP");

                    b.HasKey("MaPhieuNhap")
                        .HasName("PK_PHIEU_NHAP");

                    b.ToTable("PHIEUNHAPTHUOC", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.PhieuNhapThuocArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPHIEUNHAP");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAYNHAP");

                    b.Property<string>("NhaCungCap")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NHACUNGCAP");

                    b.ToTable("PHIEUNHAPTHUOC_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.PhongBan", b =>
                {
                    b.Property<string>("MaPb")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPB");

                    b.Property<string>("MaBp")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MABP");

                    b.Property<string>("MoTa")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MOTA");

                    b.Property<string>("TenPhongBan")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TENPHONGBAN");

                    b.HasKey("MaPb")
                        .HasName("PK_PHONG_BAN");

                    b.HasIndex("MaBp");

                    b.ToTable("PHONGBAN", (string)null);

                    b.HasData(
                        new
                        {
                            MaPb = "PBQLNS",
                            MaBp = "BPQL",
                            TenPhongBan = "Phòng quản lý tài nguyên nhân sự"
                        },
                        new
                        {
                            MaPb = "PBQLTV",
                            MaBp = "BPQL",
                            TenPhongBan = "Phòng quản lý tài vụ"
                        },
                        new
                        {
                            MaPb = "PBQLCM",
                            MaBp = "BPQL",
                            TenPhongBan = "Phòng quản lý chuyên môn"
                        },
                        new
                        {
                            MaPb = "PBTTDP",
                            MaBp = "BPTTDP",
                            TenPhongBan = "Phòng tiếp tân và điều phối"
                        },
                        new
                        {
                            MaPb = "PBKN",
                            MaBp = "BPDT",
                            TenPhongBan = "Phòng khoa nội"
                        },
                        new
                        {
                            MaPb = "PBKG",
                            MaBp = "BPDT",
                            TenPhongBan = "Phòng khoa ngoại"
                        },
                        new
                        {
                            MaPb = "PBKNHI",
                            MaBp = "BPDT",
                            TenPhongBan = "Phòng khoa nhi"
                        },
                        new
                        {
                            MaPb = "PBTTV",
                            MaBp = "BPTV",
                            TenPhongBan = "Phòng tài vụ"
                        },
                        new
                        {
                            MaPb = "PBKT",
                            MaBp = "BPKT",
                            TenPhongBan = "Phòng kế toán"
                        },
                        new
                        {
                            MaPb = "PBBT",
                            MaBp = "BPDNT",
                            TenPhongBan = "Phòng bán thuốc"
                        });
                });

            modelBuilder.Entity("QLBV.Models.PhongBanArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("MaBp")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MABP");

                    b.Property<string>("MaPb")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPB");

                    b.Property<string>("MoTa")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MOTA");

                    b.Property<string>("TenPhongBan")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TENPHONGBAN");

                    b.ToTable("PHONGBAN_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.SoKhamBenh", b =>
                {
                    b.Property<int>("MaSoKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MASOKHAM");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSoKham"));

                    b.Property<string>("MaBn")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MABN");

                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPK");

                    b.HasKey("MaSoKham");

                    b.HasIndex("MaBn");

                    b.ToTable("SOKHAMBENH", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.SoKhamBenhArchive", b =>
                {
                    b.Property<int>("MaSoKham")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MASOKHAM");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSoKham"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE");

                    b.Property<string>("MaBn")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MABN");

                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPK");

                    b.HasKey("MaSoKham");

                    b.ToTable("SOKHAMBENH_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTk")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATK");

                    b.Property<string>("LoaiTk")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LOAITK");

                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MANV");

                    b.Property<byte[]>("Mk")
                        .HasMaxLength(255)
                        .HasColumnType("RAW(255)")
                        .HasColumnName("MK");

                    b.Property<string>("TenDn")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TENDN");

                    b.HasKey("MaTk")
                        .HasName("PK_TAI_KHOAN");

                    b.HasIndex(new[] { "MaNv" }, "UQ__TaiKhoan__2725D70B0150A028")
                        .IsUnique()
                        .HasFilter("\"MANV\" IS NOT NULL");

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.TaiKhoanArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("LoaiTk")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LOAITK");

                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MANV");

                    b.Property<string>("MaTk")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATK");

                    b.Property<byte[]>("Mk")
                        .HasMaxLength(255)
                        .HasColumnType("RAW(255)")
                        .HasColumnName("MK");

                    b.Property<string>("TenDn")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TENDN");

                    b.ToTable("TAIKHOAN_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.ThuTuc", b =>
                {
                    b.Property<string>("MaThuTuc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATHUTUC");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("DONGIA");

                    b.Property<string>("TenTuc")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TENTUC");

                    b.HasKey("MaThuTuc")
                        .HasName("PK_THU_TUC");

                    b.ToTable("THUTUC", (string)null);

                    b.HasData(
                        new
                        {
                            MaThuTuc = "TT001",
                            DonGia = 150000.00m,
                            TenTuc = "Khám tổng quát"
                        },
                        new
                        {
                            MaThuTuc = "TT002",
                            DonGia = 80000.00m,
                            TenTuc = "Xét nghiệm máu"
                        },
                        new
                        {
                            MaThuTuc = "TT003",
                            DonGia = 120000.00m,
                            TenTuc = "Chụp X-quang phổi"
                        },
                        new
                        {
                            MaThuTuc = "TT004",
                            DonGia = 200000.00m,
                            TenTuc = "Siêu âm bụng tổng quát"
                        },
                        new
                        {
                            MaThuTuc = "TT005",
                            DonGia = 100000.00m,
                            TenTuc = "Đo điện tim (ECG)"
                        },
                        new
                        {
                            MaThuTuc = "TT006",
                            DonGia = 90000.00m,
                            TenTuc = "Khám tai mũi họng"
                        },
                        new
                        {
                            MaThuTuc = "TT007",
                            DonGia = 350000.00m,
                            TenTuc = "Nội soi dạ dày"
                        },
                        new
                        {
                            MaThuTuc = "TT008",
                            DonGia = 50000.00m,
                            TenTuc = "Xét nghiệm nước tiểu"
                        },
                        new
                        {
                            MaThuTuc = "TT009",
                            DonGia = 70000.00m,
                            TenTuc = "Tiêm ngừa cúm"
                        },
                        new
                        {
                            MaThuTuc = "TT010",
                            DonGia = 250000.00m,
                            TenTuc = "Khám chuyên khoa tim mạch"
                        });
                });

            modelBuilder.Entity("QLBV.Models.ThuTucArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("DONGIA");

                    b.Property<string>("MaThuTuc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATHUTUC");

                    b.Property<string>("TenTuc")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TENTUC");

                    b.ToTable("THUTUC_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.Thuoc", b =>
                {
                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATHUOC");

                    b.Property<string>("DonVi")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DONVI");

                    b.Property<string>("TenThuoc")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TENTHUOC");

                    b.HasKey("MaThuoc")
                        .HasName("PK_THUOC");

                    b.ToTable("THUOC", (string)null);

                    b.HasData(
                        new
                        {
                            MaThuoc = "TH001",
                            DonVi = "Vỉ",
                            TenThuoc = "Paracetamol 500mg"
                        },
                        new
                        {
                            MaThuoc = "TH002",
                            DonVi = "Vỉ",
                            TenThuoc = "Amoxicillin 500mg"
                        },
                        new
                        {
                            MaThuoc = "TH003",
                            DonVi = "Vỉ",
                            TenThuoc = "Vitamin C 500mg"
                        },
                        new
                        {
                            MaThuoc = "TH004",
                            DonVi = "Vỉ",
                            TenThuoc = "Ibuprofen 200mg"
                        },
                        new
                        {
                            MaThuoc = "TH005",
                            DonVi = "Vỉ",
                            TenThuoc = "Loratadine 10mg"
                        },
                        new
                        {
                            MaThuoc = "TH006",
                            DonVi = "Vỉ",
                            TenThuoc = "Omeprazole 20mg"
                        },
                        new
                        {
                            MaThuoc = "TH007",
                            DonVi = "Vỉ",
                            TenThuoc = "Salbutamol 2mg"
                        },
                        new
                        {
                            MaThuoc = "TH008",
                            DonVi = "Vỉ",
                            TenThuoc = "Cefixime 200mg"
                        },
                        new
                        {
                            MaThuoc = "TH009",
                            DonVi = "Vỉ",
                            TenThuoc = "Metronidazole 250mg"
                        },
                        new
                        {
                            MaThuoc = "TH010",
                            DonVi = "Vỉ",
                            TenThuoc = "Dextromethorphan 15mg"
                        });
                });

            modelBuilder.Entity("QLBV.Models.ThuocArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("DonVi")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DONVI");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATHUOC");

                    b.Property<string>("TenThuoc")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TENTHUOC");

                    b.ToTable("THUOC_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.ToaThuoc", b =>
                {
                    b.Property<string>("MaToaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATOATHUOC");

                    b.Property<string>("MaBacSi")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MABACSI");

                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPK");

                    b.Property<string>("NgayKe")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("NGAYKE");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("TONGTIEN");

                    b.HasKey("MaToaThuoc")
                        .HasName("PK_TOA_THUOC");

                    b.HasIndex("MaBacSi");

                    b.HasIndex("MaPk")
                        .IsUnique()
                        .HasFilter("\"MAPK\" IS NOT NULL");

                    b.ToTable("TOATHUOC", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.ToaThuocArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIONTYPE");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARCHIVEDATE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("MaBacSi")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MABACSI");

                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAPK");

                    b.Property<string>("MaToaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATOATHUOC");

                    b.Property<string>("NgayKe")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("NGAYKE");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("TONGTIEN");

                    b.ToTable("TOATHUOC_ARCHIVE", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.User_Model.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ACCESSFAILEDCOUNT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CONCURRENCYSTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("EMAILCONFIRMED");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("LOCKOUTENABLED");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("LOCKOUTEND");

                    b.Property<string>("MaNv")
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MANV");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("NORMALIZEDEMAIL");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("NORMALIZEDUSERNAME");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PASSWORDHASH");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PHONENUMBER");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PHONENUMBERCONFIRMED");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SECURITYSTAMP");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("TWOFACTORENABLED");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("MaNv")
                        .IsUnique()
                        .HasFilter("\"MANV\" IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("\"NORMALIZEDUSERNAME\" IS NOT NULL");

                    b.ToTable("ASPNETUSERS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QLBV.Models.User_Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QLBV.Models.User_Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLBV.Models.User_Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QLBV.Models.User_Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QLBV.Models.BacSi", b =>
                {
                    b.HasOne("QLBV.Models.NhanVien", "MaBsNavigation")
                        .WithOne("BacSi")
                        .HasForeignKey("QLBV.Models.BacSi", "MaBs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BACSI_NHANVIEN");

                    b.Navigation("MaBsNavigation");
                });

            modelBuilder.Entity("QLBV.Models.CaTruc", b =>
                {
                    b.HasOne("QLBV.Models.NhanVien", "NvtrucNavigation")
                        .WithMany("CaTrucs")
                        .HasForeignKey("Nvtruc")
                        .HasConstraintName("FK_CATRUC_NHANVIEN");

                    b.Navigation("NvtrucNavigation");
                });

            modelBuilder.Entity("QLBV.Models.ChiTietPhieuKham", b =>
                {
                    b.HasOne("QLBV.Models.PhieuKhamBenh", "MaPkNavigation")
                        .WithMany()
                        .HasForeignKey("MaPk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CTPK_PHIEUKHAM");

                    b.HasOne("QLBV.Models.ThuTuc", "MaTtNavigation")
                        .WithMany()
                        .HasForeignKey("MaTt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CTPK_THUTUC");

                    b.Navigation("MaPkNavigation");

                    b.Navigation("MaTtNavigation");
                });

            modelBuilder.Entity("QLBV.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QLBV.Models.PhieuNhapThuoc", "MaPhieuNhapNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CTPN_PHIEUNHAP");

                    b.HasOne("QLBV.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CTPN_THUOC");

                    b.Navigation("MaPhieuNhapNavigation");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("QLBV.Models.ChiTietToaThuoc", b =>
                {
                    b.HasOne("QLBV.Models.Thuoc", "MaThuocNavigation")
                        .WithMany()
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CTT_THUOC");

                    b.HasOne("QLBV.Models.ToaThuoc", "MaToaThuocNavigation")
                        .WithMany()
                        .HasForeignKey("MaToaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CTT_TOATHUOC");

                    b.Navigation("MaThuocNavigation");

                    b.Navigation("MaToaThuocNavigation");
                });

            modelBuilder.Entity("QLBV.Models.GiaBanThuoc", b =>
                {
                    b.HasOne("QLBV.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("GiaBanThuocs")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GIABAN_THUOC");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("QLBV.Models.Luong", b =>
                {
                    b.HasOne("QLBV.Models.NhanVien", "MaNvNavigation")
                        .WithMany("Luongs")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK_LUONG_NHANVIEN");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("QLBV.Models.NhanVien", b =>
                {
                    b.HasOne("QLBV.Models.PhongBan", "MaPbNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPb")
                        .HasConstraintName("FK_NV_PHONGBAN");

                    b.Navigation("MaPbNavigation");
                });

            modelBuilder.Entity("QLBV.Models.PhieuKhamBenh", b =>
                {
                    b.HasOne("QLBV.Models.BacSi", "BacsiNavigation")
                        .WithMany("PhieuKhamBenhs")
                        .HasForeignKey("Bacsi")
                        .HasConstraintName("FK_PK_BACSI");

                    b.HasOne("QLBV.Models.SoKhamBenh", "MaSoKhamNavigation")
                        .WithMany("PhieuKhamBenhs")
                        .HasForeignKey("MaSoKham");

                    b.HasOne("QLBV.Models.BenhNhan", "NguoiKhamNavigation")
                        .WithMany("PhieuKhamBenhs")
                        .HasForeignKey("NguoiKham")
                        .HasConstraintName("FK_PK_BENHNHAN");

                    b.Navigation("BacsiNavigation");

                    b.Navigation("MaSoKhamNavigation");

                    b.Navigation("NguoiKhamNavigation");
                });

            modelBuilder.Entity("QLBV.Models.PhongBan", b =>
                {
                    b.HasOne("QLBV.Models.BoPhan", "MaBpNavigation")
                        .WithMany("PhongBans")
                        .HasForeignKey("MaBp")
                        .HasConstraintName("FK_PB_BOPHAN");

                    b.Navigation("MaBpNavigation");
                });

            modelBuilder.Entity("QLBV.Models.SoKhamBenh", b =>
                {
                    b.HasOne("QLBV.Models.BenhNhan", "MaBnNavigation")
                        .WithMany("SoKhamBenhs")
                        .HasForeignKey("MaBn");

                    b.Navigation("MaBnNavigation");
                });

            modelBuilder.Entity("QLBV.Models.TaiKhoan", b =>
                {
                    b.HasOne("QLBV.Models.NhanVien", "MaNvNavigation")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("QLBV.Models.TaiKhoan", "MaNv")
                        .HasConstraintName("FK_TK_NHANVIEN");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("QLBV.Models.ToaThuoc", b =>
                {
                    b.HasOne("QLBV.Models.BacSi", "MaBacSiNavigation")
                        .WithMany("ToaThuocs")
                        .HasForeignKey("MaBacSi")
                        .HasConstraintName("FK_TOATHUOC_BACSI");

                    b.HasOne("QLBV.Models.PhieuKhamBenh", "MaPkNavigation")
                        .WithOne("ToaThuoc")
                        .HasForeignKey("QLBV.Models.ToaThuoc", "MaPk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_TOATHUOC_PHIEUKHAM");

                    b.Navigation("MaBacSiNavigation");

                    b.Navigation("MaPkNavigation");
                });

            modelBuilder.Entity("QLBV.Models.User_Model.ApplicationUser", b =>
                {
                    b.HasOne("QLBV.Models.NhanVien", "NhanVien")
                        .WithOne("User")
                        .HasForeignKey("QLBV.Models.User_Model.ApplicationUser", "MaNv")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_USER_NHANVIEN");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLBV.Models.BacSi", b =>
                {
                    b.Navigation("PhieuKhamBenhs");

                    b.Navigation("ToaThuocs");
                });

            modelBuilder.Entity("QLBV.Models.BenhNhan", b =>
                {
                    b.Navigation("PhieuKhamBenhs");

                    b.Navigation("SoKhamBenhs");
                });

            modelBuilder.Entity("QLBV.Models.BoPhan", b =>
                {
                    b.Navigation("PhongBans");
                });

            modelBuilder.Entity("QLBV.Models.NhanVien", b =>
                {
                    b.Navigation("BacSi");

                    b.Navigation("CaTrucs");

                    b.Navigation("Luongs");

                    b.Navigation("TaiKhoan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLBV.Models.PhieuKhamBenh", b =>
                {
                    b.Navigation("ToaThuoc");
                });

            modelBuilder.Entity("QLBV.Models.PhieuNhapThuoc", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QLBV.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QLBV.Models.SoKhamBenh", b =>
                {
                    b.Navigation("PhieuKhamBenhs");
                });

            modelBuilder.Entity("QLBV.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("GiaBanThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
