/*** DBCHINH***/
CREATE PLUGGABLE DATABASE QLBV
ADMIN USER Admin IDENTIFIED BY 123456

ALTER PLUGGABLE DATABASE QLBV OPEN;

/***DB phụ***/
SELECT name, open_mode FROM v$pdbs;

ALTER SESSION SET CONTAINER = QLBV;

GRANT CONNECT, RESOURCE TO C##VAULT;

GRANT DROP ANY TABLE TO C##VAULT;

GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO C##VAULT;

GRANT UNLIMITED TABLESPACE TO C##VAULT;

GRANT SELECT ANY DICTIONARY TO C##VAULT;

GRANT DBA TO C##VAULT;

CREATE USER Vault IDENTIFIED BY "Vault@123456#";

GRANT CONNECT, RESOURCE TO Vault;
GRANT UNLIMITED TABLESPACE TO Vault;

/*** Test tạo bảng***/
CREATE TABLE Testing (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(50)
);
ALTER DATABASE OPEN;

ALTER SESSION SET CONTAINER = CDB$ROOT;
/*** Cách xóa PDB *** thực hiện trên cdb***/
ALTER PLUGGABLE DATABASE QLBV CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE QLBV INCLUDING DATAFILES;

